// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj1m6rE4sYiaxcLRbaUXV9LOU4kporBss',
    appId: '1:1067611827826:web:84ab10d8198408bebf1ceb',
    messagingSenderId: '1067611827826',
    projectId: 'stageprojetdev-f3043',
    authDomain: 'stageprojetdev-f3043.firebaseapp.com',
    storageBucket: 'stageprojetdev-f3043.appspot.com',
    measurementId: 'G-E9VFDKNPXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rll7f1vp6Dr_mVAeJ1h-3PIyt6lmkzs',
    appId: '1:1067611827826:android:91fd87aa4e600a1dbf1ceb',
    messagingSenderId: '1067611827826',
    projectId: 'stageprojetdev-f3043',
    storageBucket: 'stageprojetdev-f3043.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjzqcfCWzZ4EdoyUfNC2Wtgpy_NJakksg',
    appId: '1:1067611827826:ios:3c6fc8122300aef4bf1ceb',
    messagingSenderId: '1067611827826',
    projectId: 'stageprojetdev-f3043',
    storageBucket: 'stageprojetdev-f3043.appspot.com',
    iosClientId: '1067611827826-k7ls1uujqnt1oq3ene97qdrlanfafvib.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjzqcfCWzZ4EdoyUfNC2Wtgpy_NJakksg',
    appId: '1:1067611827826:ios:0924ad166feae47cbf1ceb',
    messagingSenderId: '1067611827826',
    projectId: 'stageprojetdev-f3043',
    storageBucket: 'stageprojetdev-f3043.appspot.com',
    iosClientId: '1067611827826-1rbj8q672i01289j1bkkkofnofemkd3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetdev.RunnerTests',
  );
}
